---
language: node_js
node_js:
  - 0.8

before_install:
# Install coffee and server
  - "npm install -g coffee-script serve"

# Install CasperJS
  - "git clone git://github.com/n1k0/casperjs.git"
  - "cd casperjs"
  - "git checkout tags/1.0.1"
  - "sudo ln -sf `pwd`/bin/casperjs /usr/local/bin/casperjs"
  - "cd .."

before_script:
  - "coffee -c dynworker.coffee"    # Don't rely on repo
  - "serve -p 158080 &"

script:
  - "casperjs test --direct test"
