// Generated by CoffeeScript 1.4.0

/** libworker.js
 *
 * Ver: 1.1.1
 * Who: Félix Saparelli
 * Web: https://github.com/passcod/libworker.js
 *
 * Released in the Public Domain
 * https://passcod.net/license.html
*/


(function() {
  var Thread, root;

  root = this;

  this.addEventListener("message", function(e) {
    var data;
    data = String(e.data);
    if (data.length < 5) {
      return;
    }
    if (data.slice(0, 5) !== "eval:") {
      return;
    }
    return root["eval"].call(root, data.slice(5));
  });

  this.libworker = (function() {

    function libworker(metal) {
      this.metal = metal != null ? metal : new Worker(libworker.src);
    }

    libworker.prototype.send = function(msg) {
      return this.metal.postMessage(msg);
    };

    libworker.prototype["eval"] = function(val) {
      return this.send("eval:" + val);
    };

    libworker.src = "data:text/javascript;base64,dmFyIGI7Yj10aGlzO" + "3RoaXMuYWRkRXZlbnRMaXN0ZW5lcigibWVzc2FnZSIsZn" + "VuY3Rpb24oYSl7YT1TdHJpbmcoYS5kYXRhKTtpZighKDU" + "+YS5sZW5ndGgpJiYiZXZhbDoiPT09YS5zbGljZSgwLDUp" + "KXJldHVybiBiLmV2YWwuY2FsbChiLGEuc2xpY2UoNSkpfSk7";

    return libworker;

  })();

  /** DynWorker
   *
   * Ver: 2.0.0-pre
   * Who: Félix Saparelli
   * Web: https://passcod.net/DynWorker
   * Git: https://github.com/passcod/DynWorker
   *
   * Released in the Public Domain
   * https://passcod.net/license.html
  */


  Thread = (function() {

    function Thread() {
      this.worker = new libworker;
      this.worker["eval"]("self.onmessage = function (e) {  if (e.data.slice(0,5) !== 'dyno:') return;  var data = e.data.slice(5);  };");
    }

    return Thread;

  })();

}).call(this);
